/********************************************************************
  APG - an ABNF Parser Generator
  Copyright (C) 2009 Coast to Coast Research, Inc.
 
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 2 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License
  along with this program.  If not, see
  <http://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
  or write to the Free Software Foundation, Inc.,
  51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
  
	 created: Sat May 30 14:26:46 2009
	filename: SIP.h
	  author: Lowell Thomas
	          lowell@coasttocoastresearch.com
	          http://www.coasttocoastresearch.com

	 purpose: Header file for parser SIP.

*********************************************************************/
#ifndef SIP_h
#define SIP_h

// rule name IDs
#define RULE_SIP_SIP_MESSAGE 0
#define RULE_SIP_BLANKSPACE 1
#define RULE_SIP_REQUEST 2
#define RULE_SIP_REQUEST_LINE 3
#define RULE_SIP_SIP_VERSION 4
#define RULE_SIP_INVITEM 5
#define RULE_SIP_ACKM 6
#define RULE_SIP_OPTIONSM 7
#define RULE_SIP_BYEM 8
#define RULE_SIP_CANCELM 9
#define RULE_SIP_REGISTERM 10
#define RULE_SIP_METHOD 11
#define RULE_SIP_EXTENSION_METHOD 12
#define RULE_SIP_RESPONSE 13
#define RULE_SIP_STATUS_LINE 14
#define RULE_SIP_STATUS_CODE 15
#define RULE_SIP_REASON_PHRASE 16
#define RULE_SIP_SIP_URI 17
#define RULE_SIP_SIPS_URI 18
#define RULE_SIP_USERINFO 19
#define RULE_SIP_USER 20
#define RULE_SIP_USER_UNRESERVED 21
#define RULE_SIP_PASSWORD 22
#define RULE_SIP_HOSTPORT 23
#define RULE_SIP_HOST 24
#define RULE_SIP_HOSTNAME 25
#define RULE_SIP_DOMAINLABEL 26
#define RULE_SIP_TOPLABEL 27
#define RULE_SIP_PORT 28
#define RULE_SIP_URI_PARAMETERS 29
#define RULE_SIP_URI_PARAMETER 30
#define RULE_SIP_TRANSPORT_PARAM 31
#define RULE_SIP_OTHER_TRANSPORT 32
#define RULE_SIP_USER_PARAM 33
#define RULE_SIP_OTHER_USER 34
#define RULE_SIP_METHOD_PARAM 35
#define RULE_SIP_TTL_PARAM 36
#define RULE_SIP_MADDR_PARAM 37
#define RULE_SIP_LR_PARAM 38
#define RULE_SIP_OTHER_PARAM 39
#define RULE_SIP_PNAME 40
#define RULE_SIP_PVALUE 41
#define RULE_SIP_PARAMCHAR 42
#define RULE_SIP_PARAM_UNRESERVED 43
#define RULE_SIP_HEADERS 44
#define RULE_SIP_HEADER 45
#define RULE_SIP_HNAME 46
#define RULE_SIP_HVALUE 47
#define RULE_SIP_HNV_UNRESERVED 48
#define RULE_SIP_REQUEST_URI 49
#define RULE_SIP_ABSOLUTEURI 50
#define RULE_SIP_HIER_PART 51
#define RULE_SIP_NET_PATH 52
#define RULE_SIP_ABS_PATH 53
#define RULE_SIP_OPAQUE_PART 54
#define RULE_SIP_URIC 55
#define RULE_SIP_URIC_NO_SLASH 56
#define RULE_SIP_PATH_SEGMENTS 57
#define RULE_SIP_SEGMENT 58
#define RULE_SIP_PARAM 59
#define RULE_SIP_PCHAR 60
#define RULE_SIP_SCHEME 61
#define RULE_SIP_AUTHORITY 62
#define RULE_SIP_SRVR 63
#define RULE_SIP_REG_NAME 64
#define RULE_SIP_QUERY 65
#define RULE_SIP_IPV4ADDRESS 66
#define RULE_SIP_IPV6REFERENCE 67
#define RULE_SIP_IPV6ADDRESS 68
#define RULE_SIP_MESSAGE_HEADER 69
#define RULE_SIP_ACCEPT 70
#define RULE_SIP_ACCEPT_RANGE 71
#define RULE_SIP_MEDIA_RANGE 72
#define RULE_SIP_ACCEPT_PARAM 73
#define RULE_SIP_QVALUE 74
#define RULE_SIP_GENERIC_PARAM 75
#define RULE_SIP_GEN_VALUE 76
#define RULE_SIP_ACCEPT_ENCODING 77
#define RULE_SIP_ENCODING 78
#define RULE_SIP_CODINGS 79
#define RULE_SIP_CONTENT_CODING 80
#define RULE_SIP_ACCEPT_LANGUAGE 81
#define RULE_SIP_LANGUAGE 82
#define RULE_SIP_LANGUAGE_RANGE 83
#define RULE_SIP_ALERT_INFO 84
#define RULE_SIP_ALERT_PARAM 85
#define RULE_SIP_ALLOW 86
#define RULE_SIP_AUTHORIZATION 87
#define RULE_SIP_CREDENTIALS 88
#define RULE_SIP_DIGEST_RESPONSE 89
#define RULE_SIP_DIG_RESP 90
#define RULE_SIP_USERNAME 91
#define RULE_SIP_USERNAME_VALUE 92
#define RULE_SIP_DIGEST_URI 93
#define RULE_SIP_DIGEST_URI_VALUE 94
#define RULE_SIP_MESSAGE_QOP 95
#define RULE_SIP_CNONCE 96
#define RULE_SIP_CNONCE_VALUE 97
#define RULE_SIP_NONCE_COUNT 98
#define RULE_SIP_NC_VALUE 99
#define RULE_SIP_DRESPONSE 100
#define RULE_SIP_REQUEST_DIGEST 101
#define RULE_SIP_AUTH_PARAM 102
#define RULE_SIP_AUTH_PARAM_NAME 103
#define RULE_SIP_OTHER_RESPONSE 104
#define RULE_SIP_AUTH_SCHEME 105
#define RULE_SIP_AUTHENTICATION_INFO 106
#define RULE_SIP_AINFO 107
#define RULE_SIP_NEXTNONCE 108
#define RULE_SIP_RESPONSE_AUTH 109
#define RULE_SIP_RESPONSE_DIGEST 110
#define RULE_SIP_CALL_ID 111
#define RULE_SIP_CALLID 112
#define RULE_SIP_CALL_INFO 113
#define RULE_SIP_INFO 114
#define RULE_SIP_INFO_PARAM 115
#define RULE_SIP_CONTACT 116
#define RULE_SIP_CONTACT_PARAM 117
#define RULE_SIP_NAME_ADDR 118
#define RULE_SIP_ADDR_SPEC 119
#define RULE_SIP_DISPLAY_NAME 120
#define RULE_SIP_D_NAME 121
#define RULE_SIP_CONTACT_PARAMS 122
#define RULE_SIP_C_P_Q 123
#define RULE_SIP_C_P_EXPIRES 124
#define RULE_SIP_CONTACT_EXTENSION 125
#define RULE_SIP_DELTA_SECONDS 126
#define RULE_SIP_CONTENT_DISPOSITION 127
#define RULE_SIP_DISP_TYPE 128
#define RULE_SIP_DISP_PARAM 129
#define RULE_SIP_HANDLING_PARAM 130
#define RULE_SIP_OTHER_HANDLING 131
#define RULE_SIP_DISP_EXTENSION_TOKEN 132
#define RULE_SIP_CONTENT_ENCODING 133
#define RULE_SIP_CONTENT_LANGUAGE 134
#define RULE_SIP_LANGUAGE_TAG 135
#define RULE_SIP_PRIMARY_TAG 136
#define RULE_SIP_SUBTAG 137
#define RULE_SIP_CONTENT_LENGTH 138
#define RULE_SIP_CONTENT_TYPE 139
#define RULE_SIP_MEDIA_TYPE 140
#define RULE_SIP_M_TYPE 141
#define RULE_SIP_DISCRETE_TYPE 142
#define RULE_SIP_COMPOSITE_TYPE 143
#define RULE_SIP_EXTENSION_TOKEN 144
#define RULE_SIP_IETF_TOKEN 145
#define RULE_SIP_X_TOKEN 146
#define RULE_SIP_M_SUBTYPE 147
#define RULE_SIP_IANA_TOKEN 148
#define RULE_SIP_M_PARAMETER 149
#define RULE_SIP_M_ATTRIBUTE 150
#define RULE_SIP_M_VALUE 151
#define RULE_SIP_CSEQ 152
#define RULE_SIP_DATE 153
#define RULE_SIP_SIP_DATE 154
#define RULE_SIP_RFC1123_DATE 155
#define RULE_SIP_DATE1 156
#define RULE_SIP_TIME 157
#define RULE_SIP_WKDAY 158
#define RULE_SIP_MONTH 159
#define RULE_SIP_ERROR_INFO 160
#define RULE_SIP_ERROR_URI 161
#define RULE_SIP_EXPIRES 162
#define RULE_SIP_FROM 163
#define RULE_SIP_FROM_SPEC 164
#define RULE_SIP_FROM_PARAM 165
#define RULE_SIP_TAG_PARAM 166
#define RULE_SIP_IN_REPLY_TO 167
#define RULE_SIP_MAX_FORWARDS 168
#define RULE_SIP_MIME_VERSION 169
#define RULE_SIP_MIN_EXPIRES 170
#define RULE_SIP_ORGANIZATION 171
#define RULE_SIP_PRIORITY 172
#define RULE_SIP_PRIORITY_VALUE 173
#define RULE_SIP_OTHER_PRIORITY 174
#define RULE_SIP_PROXY_AUTHENTICATE 175
#define RULE_SIP_CHALLENGE 176
#define RULE_SIP_OTHER_CHALLENGE 177
#define RULE_SIP_DIGEST_CLN 178
#define RULE_SIP_REALM 179
#define RULE_SIP_REALM_VALUE 180
#define RULE_SIP_DOMAIN 181
#define RULE_SIP_URI 182
#define RULE_SIP_NONCE 183
#define RULE_SIP_NONCE_VALUE 184
#define RULE_SIP_OPAQUE 185
#define RULE_SIP_STALE 186
#define RULE_SIP_ALGORITHM 187
#define RULE_SIP_QOP_OPTIONS 188
#define RULE_SIP_QOP_VALUE 189
#define RULE_SIP_PROXY_AUTHORIZATION 190
#define RULE_SIP_PROXY_REQUIRE 191
#define RULE_SIP_OPTION_TAG 192
#define RULE_SIP_RECORD_ROUTE 193
#define RULE_SIP_REC_ROUTE 194
#define RULE_SIP_RR_PARAM 195
#define RULE_SIP_REPLY_TO 196
#define RULE_SIP_RPLYTO_SPEC 197
#define RULE_SIP_RPLYTO_PARAM 198
#define RULE_SIP_REQUIRE 199
#define RULE_SIP_RETRY_AFTER 200
#define RULE_SIP_RETRY_PARAM 201
#define RULE_SIP_ROUTE 202
#define RULE_SIP_ROUTE_PARAM 203
#define RULE_SIP_SERVER 204
#define RULE_SIP_SERVER_VAL 205
#define RULE_SIP_PRODUCT 206
#define RULE_SIP_PRODUCT_VERSION 207
#define RULE_SIP_SUBJECT 208
#define RULE_SIP_SUPPORTED 209
#define RULE_SIP_TIMESTAMP 210
#define RULE_SIP_DELAY 211
#define RULE_SIP_TO 212
#define RULE_SIP_TO_PARAM 213
#define RULE_SIP_UNSUPPORTED 214
#define RULE_SIP_USER_AGENT 215
#define RULE_SIP_VIA 216
#define RULE_SIP_VIA_PARM 217
#define RULE_SIP_VIA_PARAMS 218
#define RULE_SIP_VIA_TTL 219
#define RULE_SIP_VIA_MADDR 220
#define RULE_SIP_VIA_RECEIVED 221
#define RULE_SIP_VIA_BRANCH 222
#define RULE_SIP_VIA_EXTENSION 223
#define RULE_SIP_SENT_PROTOCOL 224
#define RULE_SIP_PROTOCOL_NAME 225
#define RULE_SIP_PROTOCOL_VERSION 226
#define RULE_SIP_TRANSPORT 227
#define RULE_SIP_SENT_BY 228
#define RULE_SIP_TTL 229
#define RULE_SIP_WARNING 230
#define RULE_SIP_WARNING_VALUE 231
#define RULE_SIP_WARN_CODE 232
#define RULE_SIP_WARN_AGENT 233
#define RULE_SIP_WARN_TEXT 234
#define RULE_SIP_PSEUDONYM 235
#define RULE_SIP_WWW_AUTHENTICATE 236
#define RULE_SIP_EXTENSION_HEADER 237
#define RULE_SIP_HEADER_NAME 238
#define RULE_SIP_HEADER_VALUE 239
#define RULE_SIP_MESSAGE_BODY 240
#define RULE_SIP_TELEPHONE_SUBSCRIBER 241
#define RULE_SIP_GLOBAL_PHONE_NUMBER 242
#define RULE_SIP_BASE_PHONE_NUMBER 243
#define RULE_SIP_LOCAL_PHONE_NUMBER 244
#define RULE_SIP_ISDN_SUBADDRESS 245
#define RULE_SIP_POST_DIAL 246
#define RULE_SIP_AREA_SPECIFIER 247
#define RULE_SIP_PHONE_CONTEXT_TAG 248
#define RULE_SIP_PHONE_CONTEXT_IDENT 249
#define RULE_SIP_NETWORK_PREFIX 250
#define RULE_SIP_GLOBAL_NETWORK_PREFIX 251
#define RULE_SIP_LOCAL_NETWORK_PREFIX 252
#define RULE_SIP_PRIVATE_PREFIX 253
#define RULE_SIP_SERVICE_PROVIDER 254
#define RULE_SIP_PROVIDER_TAG 255
#define RULE_SIP_PROVIDER_HOSTNAME 256
#define RULE_SIP_FUTURE_EXTENSION 257
#define RULE_SIP_TOKEN_CHAR 258
#define RULE_SIP_TEL_QUOTED_STRING 259
#define RULE_SIP_PHONEDIGIT 260
#define RULE_SIP_VISUAL_SEPARATOR 261
#define RULE_SIP_PAUSE_CHARACTER 262
#define RULE_SIP_ONE_SECOND_PAUSE 263
#define RULE_SIP_WAIT_FOR_DIAL_TONE 264
#define RULE_SIP_DTMF_DIGIT 265
#define RULE_SIP_RFC1035DOMAIN 266
#define RULE_SIP_RFC1035SUBDOMAIN 267
#define RULE_SIP_RFC1035LABEL 268
#define RULE_SIP_ALPHANUM 269
#define RULE_SIP_RESERVED 270
#define RULE_SIP_UNRESERVED 271
#define RULE_SIP_MARK 272
#define RULE_SIP_ESCAPED 273
#define RULE_SIP_TEXT_UTF8_TRIM 274
#define RULE_SIP_TEXT_UTF8CHAR 275
#define RULE_SIP_UTF8_NONASCII 276
#define RULE_SIP_UTF8_CONT 277
#define RULE_SIP_TOKEN 278
#define RULE_SIP_WORD 279
#define RULE_SIP_HCOLON 280
#define RULE_SIP_LHEX 281
#define RULE_SIP_STAR 282
#define RULE_SIP_SLASH 283
#define RULE_SIP_EQUAL 284
#define RULE_SIP_LPAREN 285
#define RULE_SIP_RPAREN 286
#define RULE_SIP_RAQUOT 287
#define RULE_SIP_LAQUOT 288
#define RULE_SIP_COMMA 289
#define RULE_SIP_SEMI 290
#define RULE_SIP_COLON 291
#define RULE_SIP_LDQUOT 292
#define RULE_SIP_RDQUOT 293
#define RULE_SIP_COMMENT 294
#define RULE_SIP_CTEXT 295
#define RULE_SIP_QUOTED_STRING 296
#define RULE_SIP_Q_STRING 297
#define RULE_SIP_QDTEXT 298
#define RULE_SIP_QUOTED_PAIR 299
#define RULE_SIP_LWS 300
#define RULE_SIP_SWS 301
#define RULE_SIP_WSP 302
#define RULE_SIP_ALPHA 303
#define RULE_SIP_CHAR 304
#define RULE_SIP_CR 305
#define RULE_SIP_CRLF 306
#define RULE_SIP_DIGIT 307
#define RULE_SIP_DQUOTE 308
#define RULE_SIP_HEXDIG 309
#define RULE_SIP_LF 310
#define RULE_SIP_OCTET 311
#define RULE_SIP_SP 312
#define RULE_COUNT_SIP 313

// uniquely named pointer to parser initialization data
extern void* vpParserInit_SIP;

#endif // SIP_h
