# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_smallmgcapi', [dirname(__file__)])
        except ImportError:
            import _smallmgcapi
            return _smallmgcapi
        if fp is not None:
            try:
                _mod = imp.load_module('_smallmgcapi', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _smallmgcapi = swig_import_helper()
    del swig_import_helper
else:
    import _smallmgcapi
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


SmallMGC_API_COMMAND_CONFIG_SMALLMGC_IP = _smallmgcapi.SmallMGC_API_COMMAND_CONFIG_SMALLMGC_IP
SmallMGC_API_COMMAND_CONFIG_SMALLMGC_GENERAL = _smallmgcapi.SmallMGC_API_COMMAND_CONFIG_SMALLMGC_GENERAL
SmallMGC_API_COMMAND_CONFIG_SMALLMGC_DIGITMAP = _smallmgcapi.SmallMGC_API_COMMAND_CONFIG_SMALLMGC_DIGITMAP
SmallMGC_API_COMMAND_CONFIG_SMALLMGC_SA = _smallmgcapi.SmallMGC_API_COMMAND_CONFIG_SMALLMGC_SA
SmallMGC_API_COMMAND_CONFIG_GATEWAY_IP = _smallmgcapi.SmallMGC_API_COMMAND_CONFIG_GATEWAY_IP
SmallMGC_API_COMMAND_CONFIG_GATEWAY_GENERAL = _smallmgcapi.SmallMGC_API_COMMAND_CONFIG_GATEWAY_GENERAL
SmallMGC_API_COMMAND_CONFIG_ADD_GATEWAY = _smallmgcapi.SmallMGC_API_COMMAND_CONFIG_ADD_GATEWAY
SmallMGC_API_COMMAND_CONFIG_REMOVE_GATEWAY = _smallmgcapi.SmallMGC_API_COMMAND_CONFIG_REMOVE_GATEWAY
SmallMGC_API_COMMAND_CONFIG_BLOCK_GATEWAY = _smallmgcapi.SmallMGC_API_COMMAND_CONFIG_BLOCK_GATEWAY
SmallMGC_API_COMMAND_CONFIG_SUBSCRIBER_GENERAL = _smallmgcapi.SmallMGC_API_COMMAND_CONFIG_SUBSCRIBER_GENERAL
SmallMGC_API_COMMAND_CONFIG_ADD_SUBSCRIBER = _smallmgcapi.SmallMGC_API_COMMAND_CONFIG_ADD_SUBSCRIBER
SmallMGC_API_COMMAND_CONFIG_REMOVE_SUBSCRIBER = _smallmgcapi.SmallMGC_API_COMMAND_CONFIG_REMOVE_SUBSCRIBER
SmallMGC_API_COMMAND_STATUS_SMALLMGC = _smallmgcapi.SmallMGC_API_COMMAND_STATUS_SMALLMGC
SmallMGC_API_COMMAND_STATUS_GATEWAY = _smallmgcapi.SmallMGC_API_COMMAND_STATUS_GATEWAY
SmallMGC_API_COMMAND_STATUS_SUBSCRIBER = _smallmgcapi.SmallMGC_API_COMMAND_STATUS_SUBSCRIBER
SmallMGC_API_COMMAND_STATUS_SUBSCRIBER_INSERVICE = _smallmgcapi.SmallMGC_API_COMMAND_STATUS_SUBSCRIBER_INSERVICE
SmallMGC_API_COMMAND_STATUS_SUBSCRIBER_OUTSERVICE_FORCED = _smallmgcapi.SmallMGC_API_COMMAND_STATUS_SUBSCRIBER_OUTSERVICE_FORCED
SmallMGC_API_COMMAND_STATUS_SUBSCRIBER_OUTSERVICE = _smallmgcapi.SmallMGC_API_COMMAND_STATUS_SUBSCRIBER_OUTSERVICE
SmallMGC_API_AlARM_SMALLMGC = _smallmgcapi.SmallMGC_API_AlARM_SMALLMGC
SmallMGC_API_AlARM_GATEWAY = _smallmgcapi.SmallMGC_API_AlARM_GATEWAY
SmallMGC_API_AlARM_SUBSCRIBER = _smallmgcapi.SmallMGC_API_AlARM_SUBSCRIBER
SmallMGC_API_TEST_START = _smallmgcapi.SmallMGC_API_TEST_START
SmallMGC_API_TEST_STOP = _smallmgcapi.SmallMGC_API_TEST_STOP
SmallMGC_API_TEST_RESULT = _smallmgcapi.SmallMGC_API_TEST_RESULT
SmallMGC_API_SEND_RAW = _smallmgcapi.SmallMGC_API_SEND_RAW
SmallMGC_API_RECEIVED_NOTIFY = _smallmgcapi.SmallMGC_API_RECEIVED_NOTIFY
SmallMGC_API_RECEIVED_MODIFY = _smallmgcapi.SmallMGC_API_RECEIVED_MODIFY
SmallMGC_API_RECEIVED_ADD = _smallmgcapi.SmallMGC_API_RECEIVED_ADD
SmallMGC_API_RECEIVED_SUBTRACT = _smallmgcapi.SmallMGC_API_RECEIVED_SUBTRACT
SmallMGC_API_RECEIVED_MOVE = _smallmgcapi.SmallMGC_API_RECEIVED_MOVE
SmallMGC_API_RECEIVED_AUDITVALUE = _smallmgcapi.SmallMGC_API_RECEIVED_AUDITVALUE
SmallMGC_API_RECEIVED_SERVICECHANGE = _smallmgcapi.SmallMGC_API_RECEIVED_SERVICECHANGE
SmallMGC_API_RECEIVED_PENDING = _smallmgcapi.SmallMGC_API_RECEIVED_PENDING
SmallMGC_API_RECEIVED_ERROR = _smallmgcapi.SmallMGC_API_RECEIVED_ERROR
SmallMGC_SUBSCRIBER_ALARM_BLOCKED = _smallmgcapi.SmallMGC_SUBSCRIBER_ALARM_BLOCKED
SmallMGC_SUBSCRIBER_ALARM_UNDEFINED = _smallmgcapi.SmallMGC_SUBSCRIBER_ALARM_UNDEFINED
SmallMGC_GATEWAY_ALARM_H248Association = _smallmgcapi.SmallMGC_GATEWAY_ALARM_H248Association
SmallMGC_GATEWAY_ALARM_IUAAssociation = _smallmgcapi.SmallMGC_GATEWAY_ALARM_IUAAssociation
SmallMGC_GATEWAY_ALARM_UNDEFINED = _smallmgcapi.SmallMGC_GATEWAY_ALARM_UNDEFINED
SmallMGC_SUBSCRIBER_PSTN = _smallmgcapi.SmallMGC_SUBSCRIBER_PSTN
SmallMGC_SUBSCRIBER_ISDNBA = _smallmgcapi.SmallMGC_SUBSCRIBER_ISDNBA
SmallMGC_SUBSCRIBER_ISDNPRA = _smallmgcapi.SmallMGC_SUBSCRIBER_ISDNPRA
SmallMGC_SUBSCRIBER_SIP = _smallmgcapi.SmallMGC_SUBSCRIBER_SIP
SmallMGC_SUBSCRIBER_UNDEFINED = _smallmgcapi.SmallMGC_SUBSCRIBER_UNDEFINED
SmallMGC_GATEWAY_STATUS_REGISTERED = _smallmgcapi.SmallMGC_GATEWAY_STATUS_REGISTERED
SmallMGC_GATEWAY_STATUS_UP = _smallmgcapi.SmallMGC_GATEWAY_STATUS_UP
SmallMGC_GATEWAY_STATUS_DOWN = _smallmgcapi.SmallMGC_GATEWAY_STATUS_DOWN
SmallMGC_GATEWAY_STATUS_LOST = _smallmgcapi.SmallMGC_GATEWAY_STATUS_LOST
SmallMGC_GATEWAY_STATUS_UNDEFINED = _smallmgcapi.SmallMGC_GATEWAY_STATUS_UNDEFINED
SmallMGC_GATEWAY_STATUS_IUA_REGISTERED = _smallmgcapi.SmallMGC_GATEWAY_STATUS_IUA_REGISTERED
SmallMGC_GATEWAY_STATUS_IUA_UP = _smallmgcapi.SmallMGC_GATEWAY_STATUS_IUA_UP
SmallMGC_GATEWAY_STATUS_IUA_DOWN = _smallmgcapi.SmallMGC_GATEWAY_STATUS_IUA_DOWN
SmallMGC_GATEWAY_STATUS_IUA_LOST = _smallmgcapi.SmallMGC_GATEWAY_STATUS_IUA_LOST
SmallMGC_GATEWAY_STATUS_IUA_UNDEFINED = _smallmgcapi.SmallMGC_GATEWAY_STATUS_IUA_UNDEFINED
SmallMGC_SUBSCRIBER_STATUS_REGISTERED = _smallmgcapi.SmallMGC_SUBSCRIBER_STATUS_REGISTERED
SmallMGC_SUBSCRIBER_STATUS_UP = _smallmgcapi.SmallMGC_SUBSCRIBER_STATUS_UP
SmallMGC_SUBSCRIBER_STATUS_DOWN = _smallmgcapi.SmallMGC_SUBSCRIBER_STATUS_DOWN
SmallMGC_SUBSCRIBER_STATUS_SHUTTINGDOWN = _smallmgcapi.SmallMGC_SUBSCRIBER_STATUS_SHUTTINGDOWN
SmallMGC_SUBSCRIBER_STATUS_UNDEFINED = _smallmgcapi.SmallMGC_SUBSCRIBER_STATUS_UNDEFINED
class SmallMGC_Api_TestReceivedMessage(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SmallMGC_Api_TestReceivedMessage, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SmallMGC_Api_TestReceivedMessage, name)
    __repr__ = _swig_repr
    __swig_setmethods__["command"] = _smallmgcapi.SmallMGC_Api_TestReceivedMessage_command_set
    __swig_getmethods__["command"] = _smallmgcapi.SmallMGC_Api_TestReceivedMessage_command_get
    if _newclass:command = _swig_property(_smallmgcapi.SmallMGC_Api_TestReceivedMessage_command_get, _smallmgcapi.SmallMGC_Api_TestReceivedMessage_command_set)
    __swig_setmethods__["transactionId"] = _smallmgcapi.SmallMGC_Api_TestReceivedMessage_transactionId_set
    __swig_getmethods__["transactionId"] = _smallmgcapi.SmallMGC_Api_TestReceivedMessage_transactionId_get
    if _newclass:transactionId = _swig_property(_smallmgcapi.SmallMGC_Api_TestReceivedMessage_transactionId_get, _smallmgcapi.SmallMGC_Api_TestReceivedMessage_transactionId_set)
    __swig_setmethods__["contextId"] = _smallmgcapi.SmallMGC_Api_TestReceivedMessage_contextId_set
    __swig_getmethods__["contextId"] = _smallmgcapi.SmallMGC_Api_TestReceivedMessage_contextId_get
    if _newclass:contextId = _swig_property(_smallmgcapi.SmallMGC_Api_TestReceivedMessage_contextId_get, _smallmgcapi.SmallMGC_Api_TestReceivedMessage_contextId_set)
    __swig_setmethods__["eventId"] = _smallmgcapi.SmallMGC_Api_TestReceivedMessage_eventId_set
    __swig_getmethods__["eventId"] = _smallmgcapi.SmallMGC_Api_TestReceivedMessage_eventId_get
    if _newclass:eventId = _swig_property(_smallmgcapi.SmallMGC_Api_TestReceivedMessage_eventId_get, _smallmgcapi.SmallMGC_Api_TestReceivedMessage_eventId_set)
    __swig_setmethods__["termId"] = _smallmgcapi.SmallMGC_Api_TestReceivedMessage_termId_set
    __swig_getmethods__["termId"] = _smallmgcapi.SmallMGC_Api_TestReceivedMessage_termId_get
    if _newclass:termId = _swig_property(_smallmgcapi.SmallMGC_Api_TestReceivedMessage_termId_get, _smallmgcapi.SmallMGC_Api_TestReceivedMessage_termId_set)
    __swig_setmethods__["event"] = _smallmgcapi.SmallMGC_Api_TestReceivedMessage_event_set
    __swig_getmethods__["event"] = _smallmgcapi.SmallMGC_Api_TestReceivedMessage_event_get
    if _newclass:event = _swig_property(_smallmgcapi.SmallMGC_Api_TestReceivedMessage_event_get, _smallmgcapi.SmallMGC_Api_TestReceivedMessage_event_set)
    __swig_setmethods__["localSdp"] = _smallmgcapi.SmallMGC_Api_TestReceivedMessage_localSdp_set
    __swig_getmethods__["localSdp"] = _smallmgcapi.SmallMGC_Api_TestReceivedMessage_localSdp_get
    if _newclass:localSdp = _swig_property(_smallmgcapi.SmallMGC_Api_TestReceivedMessage_localSdp_get, _smallmgcapi.SmallMGC_Api_TestReceivedMessage_localSdp_set)
    __swig_setmethods__["remoteSdp"] = _smallmgcapi.SmallMGC_Api_TestReceivedMessage_remoteSdp_set
    __swig_getmethods__["remoteSdp"] = _smallmgcapi.SmallMGC_Api_TestReceivedMessage_remoteSdp_get
    if _newclass:remoteSdp = _swig_property(_smallmgcapi.SmallMGC_Api_TestReceivedMessage_remoteSdp_get, _smallmgcapi.SmallMGC_Api_TestReceivedMessage_remoteSdp_set)
    def __init__(self): 
        this = _smallmgcapi.new_SmallMGC_Api_TestReceivedMessage()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _smallmgcapi.delete_SmallMGC_Api_TestReceivedMessage
    __del__ = lambda self : None;
SmallMGC_Api_TestReceivedMessage_swigregister = _smallmgcapi.SmallMGC_Api_TestReceivedMessage_swigregister
SmallMGC_Api_TestReceivedMessage_swigregister(SmallMGC_Api_TestReceivedMessage)

class SmallMGC_Api_ConfigIp(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SmallMGC_Api_ConfigIp, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SmallMGC_Api_ConfigIp, name)
    __repr__ = _swig_repr
    __swig_setmethods__["m_name"] = _smallmgcapi.SmallMGC_Api_ConfigIp_m_name_set
    __swig_getmethods__["m_name"] = _smallmgcapi.SmallMGC_Api_ConfigIp_m_name_get
    if _newclass:m_name = _swig_property(_smallmgcapi.SmallMGC_Api_ConfigIp_m_name_get, _smallmgcapi.SmallMGC_Api_ConfigIp_m_name_set)
    __swig_setmethods__["m_h248IpAddress"] = _smallmgcapi.SmallMGC_Api_ConfigIp_m_h248IpAddress_set
    __swig_getmethods__["m_h248IpAddress"] = _smallmgcapi.SmallMGC_Api_ConfigIp_m_h248IpAddress_get
    if _newclass:m_h248IpAddress = _swig_property(_smallmgcapi.SmallMGC_Api_ConfigIp_m_h248IpAddress_get, _smallmgcapi.SmallMGC_Api_ConfigIp_m_h248IpAddress_set)
    __swig_setmethods__["m_h248IpPort"] = _smallmgcapi.SmallMGC_Api_ConfigIp_m_h248IpPort_set
    __swig_getmethods__["m_h248IpPort"] = _smallmgcapi.SmallMGC_Api_ConfigIp_m_h248IpPort_get
    if _newclass:m_h248IpPort = _swig_property(_smallmgcapi.SmallMGC_Api_ConfigIp_m_h248IpPort_get, _smallmgcapi.SmallMGC_Api_ConfigIp_m_h248IpPort_set)
    __swig_setmethods__["m_h248IpDomainName"] = _smallmgcapi.SmallMGC_Api_ConfigIp_m_h248IpDomainName_set
    __swig_getmethods__["m_h248IpDomainName"] = _smallmgcapi.SmallMGC_Api_ConfigIp_m_h248IpDomainName_get
    if _newclass:m_h248IpDomainName = _swig_property(_smallmgcapi.SmallMGC_Api_ConfigIp_m_h248IpDomainName_get, _smallmgcapi.SmallMGC_Api_ConfigIp_m_h248IpDomainName_set)
    __swig_setmethods__["m_sigtranIpAddress"] = _smallmgcapi.SmallMGC_Api_ConfigIp_m_sigtranIpAddress_set
    __swig_getmethods__["m_sigtranIpAddress"] = _smallmgcapi.SmallMGC_Api_ConfigIp_m_sigtranIpAddress_get
    if _newclass:m_sigtranIpAddress = _swig_property(_smallmgcapi.SmallMGC_Api_ConfigIp_m_sigtranIpAddress_get, _smallmgcapi.SmallMGC_Api_ConfigIp_m_sigtranIpAddress_set)
    __swig_setmethods__["m_sigtranIpPort"] = _smallmgcapi.SmallMGC_Api_ConfigIp_m_sigtranIpPort_set
    __swig_getmethods__["m_sigtranIpPort"] = _smallmgcapi.SmallMGC_Api_ConfigIp_m_sigtranIpPort_get
    if _newclass:m_sigtranIpPort = _swig_property(_smallmgcapi.SmallMGC_Api_ConfigIp_m_sigtranIpPort_get, _smallmgcapi.SmallMGC_Api_ConfigIp_m_sigtranIpPort_set)
    __swig_setmethods__["m_sigtranIpDomainName"] = _smallmgcapi.SmallMGC_Api_ConfigIp_m_sigtranIpDomainName_set
    __swig_getmethods__["m_sigtranIpDomainName"] = _smallmgcapi.SmallMGC_Api_ConfigIp_m_sigtranIpDomainName_get
    if _newclass:m_sigtranIpDomainName = _swig_property(_smallmgcapi.SmallMGC_Api_ConfigIp_m_sigtranIpDomainName_get, _smallmgcapi.SmallMGC_Api_ConfigIp_m_sigtranIpDomainName_set)
    __swig_setmethods__["m_sipIpAddress"] = _smallmgcapi.SmallMGC_Api_ConfigIp_m_sipIpAddress_set
    __swig_getmethods__["m_sipIpAddress"] = _smallmgcapi.SmallMGC_Api_ConfigIp_m_sipIpAddress_get
    if _newclass:m_sipIpAddress = _swig_property(_smallmgcapi.SmallMGC_Api_ConfigIp_m_sipIpAddress_get, _smallmgcapi.SmallMGC_Api_ConfigIp_m_sipIpAddress_set)
    __swig_setmethods__["m_sipIpPort"] = _smallmgcapi.SmallMGC_Api_ConfigIp_m_sipIpPort_set
    __swig_getmethods__["m_sipIpPort"] = _smallmgcapi.SmallMGC_Api_ConfigIp_m_sipIpPort_get
    if _newclass:m_sipIpPort = _swig_property(_smallmgcapi.SmallMGC_Api_ConfigIp_m_sipIpPort_get, _smallmgcapi.SmallMGC_Api_ConfigIp_m_sipIpPort_set)
    __swig_setmethods__["m_sipIpDomainName"] = _smallmgcapi.SmallMGC_Api_ConfigIp_m_sipIpDomainName_set
    __swig_getmethods__["m_sipIpDomainName"] = _smallmgcapi.SmallMGC_Api_ConfigIp_m_sipIpDomainName_get
    if _newclass:m_sipIpDomainName = _swig_property(_smallmgcapi.SmallMGC_Api_ConfigIp_m_sipIpDomainName_get, _smallmgcapi.SmallMGC_Api_ConfigIp_m_sipIpDomainName_set)
    def __init__(self): 
        this = _smallmgcapi.new_SmallMGC_Api_ConfigIp()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _smallmgcapi.delete_SmallMGC_Api_ConfigIp
    __del__ = lambda self : None;
SmallMGC_Api_ConfigIp_swigregister = _smallmgcapi.SmallMGC_Api_ConfigIp_swigregister
SmallMGC_Api_ConfigIp_swigregister(SmallMGC_Api_ConfigIp)

class SmallMGC_Api_ConfigGeneral(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SmallMGC_Api_ConfigGeneral, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SmallMGC_Api_ConfigGeneral, name)
    __repr__ = _swig_repr
    __swig_setmethods__["m_retransmissions"] = _smallmgcapi.SmallMGC_Api_ConfigGeneral_m_retransmissions_set
    __swig_getmethods__["m_retransmissions"] = _smallmgcapi.SmallMGC_Api_ConfigGeneral_m_retransmissions_get
    if _newclass:m_retransmissions = _swig_property(_smallmgcapi.SmallMGC_Api_ConfigGeneral_m_retransmissions_get, _smallmgcapi.SmallMGC_Api_ConfigGeneral_m_retransmissions_set)
    __swig_setmethods__["m_modifybundles"] = _smallmgcapi.SmallMGC_Api_ConfigGeneral_m_modifybundles_set
    __swig_getmethods__["m_modifybundles"] = _smallmgcapi.SmallMGC_Api_ConfigGeneral_m_modifybundles_get
    if _newclass:m_modifybundles = _swig_property(_smallmgcapi.SmallMGC_Api_ConfigGeneral_m_modifybundles_get, _smallmgcapi.SmallMGC_Api_ConfigGeneral_m_modifybundles_set)
    __swig_setmethods__["m_bundlestimeout"] = _smallmgcapi.SmallMGC_Api_ConfigGeneral_m_bundlestimeout_set
    __swig_getmethods__["m_bundlestimeout"] = _smallmgcapi.SmallMGC_Api_ConfigGeneral_m_bundlestimeout_get
    if _newclass:m_bundlestimeout = _swig_property(_smallmgcapi.SmallMGC_Api_ConfigGeneral_m_bundlestimeout_get, _smallmgcapi.SmallMGC_Api_ConfigGeneral_m_bundlestimeout_set)
    __swig_setmethods__["m_busyToneDuration"] = _smallmgcapi.SmallMGC_Api_ConfigGeneral_m_busyToneDuration_set
    __swig_getmethods__["m_busyToneDuration"] = _smallmgcapi.SmallMGC_Api_ConfigGeneral_m_busyToneDuration_get
    if _newclass:m_busyToneDuration = _swig_property(_smallmgcapi.SmallMGC_Api_ConfigGeneral_m_busyToneDuration_get, _smallmgcapi.SmallMGC_Api_ConfigGeneral_m_busyToneDuration_set)
    __swig_setmethods__["m_congestionToneDuration"] = _smallmgcapi.SmallMGC_Api_ConfigGeneral_m_congestionToneDuration_set
    __swig_getmethods__["m_congestionToneDuration"] = _smallmgcapi.SmallMGC_Api_ConfigGeneral_m_congestionToneDuration_get
    if _newclass:m_congestionToneDuration = _swig_property(_smallmgcapi.SmallMGC_Api_ConfigGeneral_m_congestionToneDuration_get, _smallmgcapi.SmallMGC_Api_ConfigGeneral_m_congestionToneDuration_set)
    __swig_setmethods__["m_howlerToneDuration"] = _smallmgcapi.SmallMGC_Api_ConfigGeneral_m_howlerToneDuration_set
    __swig_getmethods__["m_howlerToneDuration"] = _smallmgcapi.SmallMGC_Api_ConfigGeneral_m_howlerToneDuration_get
    if _newclass:m_howlerToneDuration = _swig_property(_smallmgcapi.SmallMGC_Api_ConfigGeneral_m_howlerToneDuration_get, _smallmgcapi.SmallMGC_Api_ConfigGeneral_m_howlerToneDuration_set)
    def __init__(self): 
        this = _smallmgcapi.new_SmallMGC_Api_ConfigGeneral()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _smallmgcapi.delete_SmallMGC_Api_ConfigGeneral
    __del__ = lambda self : None;
SmallMGC_Api_ConfigGeneral_swigregister = _smallmgcapi.SmallMGC_Api_ConfigGeneral_swigregister
SmallMGC_Api_ConfigGeneral_swigregister(SmallMGC_Api_ConfigGeneral)

class SmallMGC_Api_ConfigDigitmap(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SmallMGC_Api_ConfigDigitmap, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SmallMGC_Api_ConfigDigitmap, name)
    __repr__ = _swig_repr
    __swig_setmethods__["m_digitmap"] = _smallmgcapi.SmallMGC_Api_ConfigDigitmap_m_digitmap_set
    __swig_getmethods__["m_digitmap"] = _smallmgcapi.SmallMGC_Api_ConfigDigitmap_m_digitmap_get
    if _newclass:m_digitmap = _swig_property(_smallmgcapi.SmallMGC_Api_ConfigDigitmap_m_digitmap_get, _smallmgcapi.SmallMGC_Api_ConfigDigitmap_m_digitmap_set)
    def __init__(self): 
        this = _smallmgcapi.new_SmallMGC_Api_ConfigDigitmap()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _smallmgcapi.delete_SmallMGC_Api_ConfigDigitmap
    __del__ = lambda self : None;
SmallMGC_Api_ConfigDigitmap_swigregister = _smallmgcapi.SmallMGC_Api_ConfigDigitmap_swigregister
SmallMGC_Api_ConfigDigitmap_swigregister(SmallMGC_Api_ConfigDigitmap)

class SmallMGC_Api_ConfigSA(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SmallMGC_Api_ConfigSA, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SmallMGC_Api_ConfigSA, name)
    __repr__ = _swig_repr
    __swig_setmethods__["m_sa_enabled"] = _smallmgcapi.SmallMGC_Api_ConfigSA_m_sa_enabled_set
    __swig_getmethods__["m_sa_enabled"] = _smallmgcapi.SmallMGC_Api_ConfigSA_m_sa_enabled_get
    if _newclass:m_sa_enabled = _swig_property(_smallmgcapi.SmallMGC_Api_ConfigSA_m_sa_enabled_get, _smallmgcapi.SmallMGC_Api_ConfigSA_m_sa_enabled_set)
    __swig_setmethods__["m_sa_timeout"] = _smallmgcapi.SmallMGC_Api_ConfigSA_m_sa_timeout_set
    __swig_getmethods__["m_sa_timeout"] = _smallmgcapi.SmallMGC_Api_ConfigSA_m_sa_timeout_get
    if _newclass:m_sa_timeout = _swig_property(_smallmgcapi.SmallMGC_Api_ConfigSA_m_sa_timeout_get, _smallmgcapi.SmallMGC_Api_ConfigSA_m_sa_timeout_set)
    __swig_setmethods__["m_sa_mainMgcIpAddress"] = _smallmgcapi.SmallMGC_Api_ConfigSA_m_sa_mainMgcIpAddress_set
    __swig_getmethods__["m_sa_mainMgcIpAddress"] = _smallmgcapi.SmallMGC_Api_ConfigSA_m_sa_mainMgcIpAddress_get
    if _newclass:m_sa_mainMgcIpAddress = _swig_property(_smallmgcapi.SmallMGC_Api_ConfigSA_m_sa_mainMgcIpAddress_get, _smallmgcapi.SmallMGC_Api_ConfigSA_m_sa_mainMgcIpAddress_set)
    __swig_setmethods__["m_sa_mainMgcIpPort"] = _smallmgcapi.SmallMGC_Api_ConfigSA_m_sa_mainMgcIpPort_set
    __swig_getmethods__["m_sa_mainMgcIpPort"] = _smallmgcapi.SmallMGC_Api_ConfigSA_m_sa_mainMgcIpPort_get
    if _newclass:m_sa_mainMgcIpPort = _swig_property(_smallmgcapi.SmallMGC_Api_ConfigSA_m_sa_mainMgcIpPort_get, _smallmgcapi.SmallMGC_Api_ConfigSA_m_sa_mainMgcIpPort_set)
    __swig_setmethods__["m_sa_mainMgcIpDomain"] = _smallmgcapi.SmallMGC_Api_ConfigSA_m_sa_mainMgcIpDomain_set
    __swig_getmethods__["m_sa_mainMgcIpDomain"] = _smallmgcapi.SmallMGC_Api_ConfigSA_m_sa_mainMgcIpDomain_get
    if _newclass:m_sa_mainMgcIpDomain = _swig_property(_smallmgcapi.SmallMGC_Api_ConfigSA_m_sa_mainMgcIpDomain_get, _smallmgcapi.SmallMGC_Api_ConfigSA_m_sa_mainMgcIpDomain_set)
    def __init__(self): 
        this = _smallmgcapi.new_SmallMGC_Api_ConfigSA()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _smallmgcapi.delete_SmallMGC_Api_ConfigSA
    __del__ = lambda self : None;
SmallMGC_Api_ConfigSA_swigregister = _smallmgcapi.SmallMGC_Api_ConfigSA_swigregister
SmallMGC_Api_ConfigSA_swigregister(SmallMGC_Api_ConfigSA)

class SmallMGC_Api_Config(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SmallMGC_Api_Config, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SmallMGC_Api_Config, name)
    __repr__ = _swig_repr
    __swig_setmethods__["m_configIp"] = _smallmgcapi.SmallMGC_Api_Config_m_configIp_set
    __swig_getmethods__["m_configIp"] = _smallmgcapi.SmallMGC_Api_Config_m_configIp_get
    if _newclass:m_configIp = _swig_property(_smallmgcapi.SmallMGC_Api_Config_m_configIp_get, _smallmgcapi.SmallMGC_Api_Config_m_configIp_set)
    __swig_setmethods__["m_configGeneral"] = _smallmgcapi.SmallMGC_Api_Config_m_configGeneral_set
    __swig_getmethods__["m_configGeneral"] = _smallmgcapi.SmallMGC_Api_Config_m_configGeneral_get
    if _newclass:m_configGeneral = _swig_property(_smallmgcapi.SmallMGC_Api_Config_m_configGeneral_get, _smallmgcapi.SmallMGC_Api_Config_m_configGeneral_set)
    __swig_setmethods__["m_configDigitmap"] = _smallmgcapi.SmallMGC_Api_Config_m_configDigitmap_set
    __swig_getmethods__["m_configDigitmap"] = _smallmgcapi.SmallMGC_Api_Config_m_configDigitmap_get
    if _newclass:m_configDigitmap = _swig_property(_smallmgcapi.SmallMGC_Api_Config_m_configDigitmap_get, _smallmgcapi.SmallMGC_Api_Config_m_configDigitmap_set)
    __swig_setmethods__["m_configSA"] = _smallmgcapi.SmallMGC_Api_Config_m_configSA_set
    __swig_getmethods__["m_configSA"] = _smallmgcapi.SmallMGC_Api_Config_m_configSA_get
    if _newclass:m_configSA = _swig_property(_smallmgcapi.SmallMGC_Api_Config_m_configSA_get, _smallmgcapi.SmallMGC_Api_Config_m_configSA_set)
    def __init__(self): 
        this = _smallmgcapi.new_SmallMGC_Api_Config()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _smallmgcapi.delete_SmallMGC_Api_Config
    __del__ = lambda self : None;
SmallMGC_Api_Config_swigregister = _smallmgcapi.SmallMGC_Api_Config_swigregister
SmallMGC_Api_Config_swigregister(SmallMGC_Api_Config)

class SmallMGC_Api_GatewayGeneral(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SmallMGC_Api_GatewayGeneral, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SmallMGC_Api_GatewayGeneral, name)
    __repr__ = _swig_repr
    __swig_setmethods__["m_gatewayCallControlMode"] = _smallmgcapi.SmallMGC_Api_GatewayGeneral_m_gatewayCallControlMode_set
    __swig_getmethods__["m_gatewayCallControlMode"] = _smallmgcapi.SmallMGC_Api_GatewayGeneral_m_gatewayCallControlMode_get
    if _newclass:m_gatewayCallControlMode = _swig_property(_smallmgcapi.SmallMGC_Api_GatewayGeneral_m_gatewayCallControlMode_get, _smallmgcapi.SmallMGC_Api_GatewayGeneral_m_gatewayCallControlMode_set)
    __swig_setmethods__["m_gatewayItPackageTimeout"] = _smallmgcapi.SmallMGC_Api_GatewayGeneral_m_gatewayItPackageTimeout_set
    __swig_getmethods__["m_gatewayItPackageTimeout"] = _smallmgcapi.SmallMGC_Api_GatewayGeneral_m_gatewayItPackageTimeout_get
    if _newclass:m_gatewayItPackageTimeout = _swig_property(_smallmgcapi.SmallMGC_Api_GatewayGeneral_m_gatewayItPackageTimeout_get, _smallmgcapi.SmallMGC_Api_GatewayGeneral_m_gatewayItPackageTimeout_set)
    __swig_setmethods__["m_gatewayItPackageEnabled"] = _smallmgcapi.SmallMGC_Api_GatewayGeneral_m_gatewayItPackageEnabled_set
    __swig_getmethods__["m_gatewayItPackageEnabled"] = _smallmgcapi.SmallMGC_Api_GatewayGeneral_m_gatewayItPackageEnabled_get
    if _newclass:m_gatewayItPackageEnabled = _swig_property(_smallmgcapi.SmallMGC_Api_GatewayGeneral_m_gatewayItPackageEnabled_get, _smallmgcapi.SmallMGC_Api_GatewayGeneral_m_gatewayItPackageEnabled_set)
    def __init__(self): 
        this = _smallmgcapi.new_SmallMGC_Api_GatewayGeneral()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _smallmgcapi.delete_SmallMGC_Api_GatewayGeneral
    __del__ = lambda self : None;
SmallMGC_Api_GatewayGeneral_swigregister = _smallmgcapi.SmallMGC_Api_GatewayGeneral_swigregister
SmallMGC_Api_GatewayGeneral_swigregister(SmallMGC_Api_GatewayGeneral)

class SmallMGC_Api_Gateway(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SmallMGC_Api_Gateway, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SmallMGC_Api_Gateway, name)
    __repr__ = _swig_repr
    __swig_setmethods__["m_gatewayIp"] = _smallmgcapi.SmallMGC_Api_Gateway_m_gatewayIp_set
    __swig_getmethods__["m_gatewayIp"] = _smallmgcapi.SmallMGC_Api_Gateway_m_gatewayIp_get
    if _newclass:m_gatewayIp = _swig_property(_smallmgcapi.SmallMGC_Api_Gateway_m_gatewayIp_get, _smallmgcapi.SmallMGC_Api_Gateway_m_gatewayIp_set)
    __swig_setmethods__["m_gatewayGeneral"] = _smallmgcapi.SmallMGC_Api_Gateway_m_gatewayGeneral_set
    __swig_getmethods__["m_gatewayGeneral"] = _smallmgcapi.SmallMGC_Api_Gateway_m_gatewayGeneral_get
    if _newclass:m_gatewayGeneral = _swig_property(_smallmgcapi.SmallMGC_Api_Gateway_m_gatewayGeneral_get, _smallmgcapi.SmallMGC_Api_Gateway_m_gatewayGeneral_set)
    def __init__(self): 
        this = _smallmgcapi.new_SmallMGC_Api_Gateway()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _smallmgcapi.delete_SmallMGC_Api_Gateway
    __del__ = lambda self : None;
SmallMGC_Api_Gateway_swigregister = _smallmgcapi.SmallMGC_Api_Gateway_swigregister
SmallMGC_Api_Gateway_swigregister(SmallMGC_Api_Gateway)

class SmallMGC_Api_GatewayStatus(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SmallMGC_Api_GatewayStatus, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SmallMGC_Api_GatewayStatus, name)
    __repr__ = _swig_repr
    __swig_setmethods__["m_gatewayIpAddress"] = _smallmgcapi.SmallMGC_Api_GatewayStatus_m_gatewayIpAddress_set
    __swig_getmethods__["m_gatewayIpAddress"] = _smallmgcapi.SmallMGC_Api_GatewayStatus_m_gatewayIpAddress_get
    if _newclass:m_gatewayIpAddress = _swig_property(_smallmgcapi.SmallMGC_Api_GatewayStatus_m_gatewayIpAddress_get, _smallmgcapi.SmallMGC_Api_GatewayStatus_m_gatewayIpAddress_set)
    __swig_setmethods__["m_h248State"] = _smallmgcapi.SmallMGC_Api_GatewayStatus_m_h248State_set
    __swig_getmethods__["m_h248State"] = _smallmgcapi.SmallMGC_Api_GatewayStatus_m_h248State_get
    if _newclass:m_h248State = _swig_property(_smallmgcapi.SmallMGC_Api_GatewayStatus_m_h248State_get, _smallmgcapi.SmallMGC_Api_GatewayStatus_m_h248State_set)
    __swig_setmethods__["m_iuaState"] = _smallmgcapi.SmallMGC_Api_GatewayStatus_m_iuaState_set
    __swig_getmethods__["m_iuaState"] = _smallmgcapi.SmallMGC_Api_GatewayStatus_m_iuaState_get
    if _newclass:m_iuaState = _swig_property(_smallmgcapi.SmallMGC_Api_GatewayStatus_m_iuaState_get, _smallmgcapi.SmallMGC_Api_GatewayStatus_m_iuaState_set)
    __swig_setmethods__["m_callsTotal"] = _smallmgcapi.SmallMGC_Api_GatewayStatus_m_callsTotal_set
    __swig_getmethods__["m_callsTotal"] = _smallmgcapi.SmallMGC_Api_GatewayStatus_m_callsTotal_get
    if _newclass:m_callsTotal = _swig_property(_smallmgcapi.SmallMGC_Api_GatewayStatus_m_callsTotal_get, _smallmgcapi.SmallMGC_Api_GatewayStatus_m_callsTotal_set)
    __swig_setmethods__["m_callOngoing"] = _smallmgcapi.SmallMGC_Api_GatewayStatus_m_callOngoing_set
    __swig_getmethods__["m_callOngoing"] = _smallmgcapi.SmallMGC_Api_GatewayStatus_m_callOngoing_get
    if _newclass:m_callOngoing = _swig_property(_smallmgcapi.SmallMGC_Api_GatewayStatus_m_callOngoing_get, _smallmgcapi.SmallMGC_Api_GatewayStatus_m_callOngoing_set)
    def __init__(self): 
        this = _smallmgcapi.new_SmallMGC_Api_GatewayStatus()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _smallmgcapi.delete_SmallMGC_Api_GatewayStatus
    __del__ = lambda self : None;
SmallMGC_Api_GatewayStatus_swigregister = _smallmgcapi.SmallMGC_Api_GatewayStatus_swigregister
SmallMGC_Api_GatewayStatus_swigregister(SmallMGC_Api_GatewayStatus)

class SmallMGC_Api_Status(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SmallMGC_Api_Status, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SmallMGC_Api_Status, name)
    __repr__ = _swig_repr
    __swig_setmethods__["m_callsTotal"] = _smallmgcapi.SmallMGC_Api_Status_m_callsTotal_set
    __swig_getmethods__["m_callsTotal"] = _smallmgcapi.SmallMGC_Api_Status_m_callsTotal_get
    if _newclass:m_callsTotal = _swig_property(_smallmgcapi.SmallMGC_Api_Status_m_callsTotal_get, _smallmgcapi.SmallMGC_Api_Status_m_callsTotal_set)
    __swig_setmethods__["m_callOngoing"] = _smallmgcapi.SmallMGC_Api_Status_m_callOngoing_set
    __swig_getmethods__["m_callOngoing"] = _smallmgcapi.SmallMGC_Api_Status_m_callOngoing_get
    if _newclass:m_callOngoing = _swig_property(_smallmgcapi.SmallMGC_Api_Status_m_callOngoing_get, _smallmgcapi.SmallMGC_Api_Status_m_callOngoing_set)
    def __init__(self): 
        this = _smallmgcapi.new_SmallMGC_Api_Status()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _smallmgcapi.delete_SmallMGC_Api_Status
    __del__ = lambda self : None;
SmallMGC_Api_Status_swigregister = _smallmgcapi.SmallMGC_Api_Status_swigregister
SmallMGC_Api_Status_swigregister(SmallMGC_Api_Status)

class SmallMGC_Api_Subscriber(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SmallMGC_Api_Subscriber, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SmallMGC_Api_Subscriber, name)
    __repr__ = _swig_repr
    __swig_setmethods__["m_gatewayIpAddress"] = _smallmgcapi.SmallMGC_Api_Subscriber_m_gatewayIpAddress_set
    __swig_getmethods__["m_gatewayIpAddress"] = _smallmgcapi.SmallMGC_Api_Subscriber_m_gatewayIpAddress_get
    if _newclass:m_gatewayIpAddress = _swig_property(_smallmgcapi.SmallMGC_Api_Subscriber_m_gatewayIpAddress_get, _smallmgcapi.SmallMGC_Api_Subscriber_m_gatewayIpAddress_set)
    __swig_setmethods__["m_subscriberName"] = _smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberName_set
    __swig_getmethods__["m_subscriberName"] = _smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberName_get
    if _newclass:m_subscriberName = _swig_property(_smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberName_get, _smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberName_set)
    __swig_setmethods__["m_subscriberType"] = _smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberType_set
    __swig_getmethods__["m_subscriberType"] = _smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberType_get
    if _newclass:m_subscriberType = _swig_property(_smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberType_get, _smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberType_set)
    __swig_setmethods__["m_subscriberTermination"] = _smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberTermination_set
    __swig_getmethods__["m_subscriberTermination"] = _smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberTermination_get
    if _newclass:m_subscriberTermination = _swig_property(_smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberTermination_get, _smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberTermination_set)
    __swig_setmethods__["m_subscriberNumber"] = _smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberNumber_set
    __swig_getmethods__["m_subscriberNumber"] = _smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberNumber_get
    if _newclass:m_subscriberNumber = _swig_property(_smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberNumber_get, _smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberNumber_set)
    __swig_setmethods__["m_subscriberNumberRangeStart"] = _smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberNumberRangeStart_set
    __swig_getmethods__["m_subscriberNumberRangeStart"] = _smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberNumberRangeStart_get
    if _newclass:m_subscriberNumberRangeStart = _swig_property(_smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberNumberRangeStart_get, _smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberNumberRangeStart_set)
    __swig_setmethods__["m_subscriberNumberRangeEnd"] = _smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberNumberRangeEnd_set
    __swig_getmethods__["m_subscriberNumberRangeEnd"] = _smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberNumberRangeEnd_get
    if _newclass:m_subscriberNumberRangeEnd = _swig_property(_smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberNumberRangeEnd_get, _smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberNumberRangeEnd_set)
    __swig_setmethods__["m_subscriberDomainName"] = _smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberDomainName_set
    __swig_getmethods__["m_subscriberDomainName"] = _smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberDomainName_get
    if _newclass:m_subscriberDomainName = _swig_property(_smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberDomainName_get, _smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberDomainName_set)
    __swig_setmethods__["m_subscriberIuaId"] = _smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberIuaId_set
    __swig_getmethods__["m_subscriberIuaId"] = _smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberIuaId_get
    if _newclass:m_subscriberIuaId = _swig_property(_smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberIuaId_get, _smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberIuaId_set)
    __swig_setmethods__["m_subscriberIuaInt"] = _smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberIuaInt_set
    __swig_getmethods__["m_subscriberIuaInt"] = _smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberIuaInt_get
    if _newclass:m_subscriberIuaInt = _swig_property(_smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberIuaInt_get, _smallmgcapi.SmallMGC_Api_Subscriber_m_subscriberIuaInt_set)
    def __init__(self): 
        this = _smallmgcapi.new_SmallMGC_Api_Subscriber()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _smallmgcapi.delete_SmallMGC_Api_Subscriber
    __del__ = lambda self : None;
SmallMGC_Api_Subscriber_swigregister = _smallmgcapi.SmallMGC_Api_Subscriber_swigregister
SmallMGC_Api_Subscriber_swigregister(SmallMGC_Api_Subscriber)

class SmallMGC_Api_SubscriberStatus(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SmallMGC_Api_SubscriberStatus, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SmallMGC_Api_SubscriberStatus, name)
    __repr__ = _swig_repr
    __swig_setmethods__["m_gatewayIpAddress"] = _smallmgcapi.SmallMGC_Api_SubscriberStatus_m_gatewayIpAddress_set
    __swig_getmethods__["m_gatewayIpAddress"] = _smallmgcapi.SmallMGC_Api_SubscriberStatus_m_gatewayIpAddress_get
    if _newclass:m_gatewayIpAddress = _swig_property(_smallmgcapi.SmallMGC_Api_SubscriberStatus_m_gatewayIpAddress_get, _smallmgcapi.SmallMGC_Api_SubscriberStatus_m_gatewayIpAddress_set)
    __swig_setmethods__["m_subscriberTermination"] = _smallmgcapi.SmallMGC_Api_SubscriberStatus_m_subscriberTermination_set
    __swig_getmethods__["m_subscriberTermination"] = _smallmgcapi.SmallMGC_Api_SubscriberStatus_m_subscriberTermination_get
    if _newclass:m_subscriberTermination = _swig_property(_smallmgcapi.SmallMGC_Api_SubscriberStatus_m_subscriberTermination_get, _smallmgcapi.SmallMGC_Api_SubscriberStatus_m_subscriberTermination_set)
    __swig_setmethods__["m_subscriberState"] = _smallmgcapi.SmallMGC_Api_SubscriberStatus_m_subscriberState_set
    __swig_getmethods__["m_subscriberState"] = _smallmgcapi.SmallMGC_Api_SubscriberStatus_m_subscriberState_get
    if _newclass:m_subscriberState = _swig_property(_smallmgcapi.SmallMGC_Api_SubscriberStatus_m_subscriberState_get, _smallmgcapi.SmallMGC_Api_SubscriberStatus_m_subscriberState_set)
    __swig_setmethods__["m_subscriberDomainName"] = _smallmgcapi.SmallMGC_Api_SubscriberStatus_m_subscriberDomainName_set
    __swig_getmethods__["m_subscriberDomainName"] = _smallmgcapi.SmallMGC_Api_SubscriberStatus_m_subscriberDomainName_get
    if _newclass:m_subscriberDomainName = _swig_property(_smallmgcapi.SmallMGC_Api_SubscriberStatus_m_subscriberDomainName_get, _smallmgcapi.SmallMGC_Api_SubscriberStatus_m_subscriberDomainName_set)
    __swig_setmethods__["m_subscriberIuaId"] = _smallmgcapi.SmallMGC_Api_SubscriberStatus_m_subscriberIuaId_set
    __swig_getmethods__["m_subscriberIuaId"] = _smallmgcapi.SmallMGC_Api_SubscriberStatus_m_subscriberIuaId_get
    if _newclass:m_subscriberIuaId = _swig_property(_smallmgcapi.SmallMGC_Api_SubscriberStatus_m_subscriberIuaId_get, _smallmgcapi.SmallMGC_Api_SubscriberStatus_m_subscriberIuaId_set)
    __swig_setmethods__["m_subscriberIuaInt"] = _smallmgcapi.SmallMGC_Api_SubscriberStatus_m_subscriberIuaInt_set
    __swig_getmethods__["m_subscriberIuaInt"] = _smallmgcapi.SmallMGC_Api_SubscriberStatus_m_subscriberIuaInt_get
    if _newclass:m_subscriberIuaInt = _swig_property(_smallmgcapi.SmallMGC_Api_SubscriberStatus_m_subscriberIuaInt_get, _smallmgcapi.SmallMGC_Api_SubscriberStatus_m_subscriberIuaInt_set)
    __swig_setmethods__["m_callsTotal"] = _smallmgcapi.SmallMGC_Api_SubscriberStatus_m_callsTotal_set
    __swig_getmethods__["m_callsTotal"] = _smallmgcapi.SmallMGC_Api_SubscriberStatus_m_callsTotal_get
    if _newclass:m_callsTotal = _swig_property(_smallmgcapi.SmallMGC_Api_SubscriberStatus_m_callsTotal_get, _smallmgcapi.SmallMGC_Api_SubscriberStatus_m_callsTotal_set)
    __swig_setmethods__["m_callOngoing"] = _smallmgcapi.SmallMGC_Api_SubscriberStatus_m_callOngoing_set
    __swig_getmethods__["m_callOngoing"] = _smallmgcapi.SmallMGC_Api_SubscriberStatus_m_callOngoing_get
    if _newclass:m_callOngoing = _swig_property(_smallmgcapi.SmallMGC_Api_SubscriberStatus_m_callOngoing_get, _smallmgcapi.SmallMGC_Api_SubscriberStatus_m_callOngoing_set)
    def __init__(self): 
        this = _smallmgcapi.new_SmallMGC_Api_SubscriberStatus()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _smallmgcapi.delete_SmallMGC_Api_SubscriberStatus
    __del__ = lambda self : None;
SmallMGC_Api_SubscriberStatus_swigregister = _smallmgcapi.SmallMGC_Api_SubscriberStatus_swigregister
SmallMGC_Api_SubscriberStatus_swigregister(SmallMGC_Api_SubscriberStatus)

class SmallMGC_Api(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SmallMGC_Api, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SmallMGC_Api, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _smallmgcapi.new_SmallMGC_Api()
        try: self.this.append(this)
        except: self.this = this
    def addGateway(self, *args): return _smallmgcapi.SmallMGC_Api_addGateway(self, *args)
    def removeGateway(self, *args): return _smallmgcapi.SmallMGC_Api_removeGateway(self, *args)
    def blockGateway(self, *args): return _smallmgcapi.SmallMGC_Api_blockGateway(self, *args)
    def addSubscriber(self, *args): return _smallmgcapi.SmallMGC_Api_addSubscriber(self, *args)
    def removeSubscriber(self, *args): return _smallmgcapi.SmallMGC_Api_removeSubscriber(self, *args)
    def blockSubscriber(self, *args): return _smallmgcapi.SmallMGC_Api_blockSubscriber(self, *args)
    def unblockSubscriber(self, *args): return _smallmgcapi.SmallMGC_Api_unblockSubscriber(self, *args)
    def shutdownSubscriber(self, *args): return _smallmgcapi.SmallMGC_Api_shutdownSubscriber(self, *args)
    def getSubscriberStatus(self, *args): return _smallmgcapi.SmallMGC_Api_getSubscriberStatus(self, *args)
    def setSubscriberStatus(self, *args): return _smallmgcapi.SmallMGC_Api_setSubscriberStatus(self, *args)
    def setGatewayStatus(self, *args): return _smallmgcapi.SmallMGC_Api_setGatewayStatus(self, *args)
    def getGatewayStatus(self, *args): return _smallmgcapi.SmallMGC_Api_getGatewayStatus(self, *args)
    def subscriberAlarmSet(self, *args): return _smallmgcapi.SmallMGC_Api_subscriberAlarmSet(self, *args)
    def subscriberAlarmClear(self, *args): return _smallmgcapi.SmallMGC_Api_subscriberAlarmClear(self, *args)
    def gatewayAlarmSet(self, *args): return _smallmgcapi.SmallMGC_Api_gatewayAlarmSet(self, *args)
    def gatewayAlarmClear(self, *args): return _smallmgcapi.SmallMGC_Api_gatewayAlarmClear(self, *args)
    __swig_destroy__ = _smallmgcapi.delete_SmallMGC_Api
    __del__ = lambda self : None;
    def setConfigSA(self, *args): return _smallmgcapi.SmallMGC_Api_setConfigSA(self, *args)
    def setConfigDigitmap(self, *args): return _smallmgcapi.SmallMGC_Api_setConfigDigitmap(self, *args)
    def setConfigGeneral(self, *args): return _smallmgcapi.SmallMGC_Api_setConfigGeneral(self, *args)
    def setConfigIp(self, *args): return _smallmgcapi.SmallMGC_Api_setConfigIp(self, *args)
    def getConfigSA(self): return _smallmgcapi.SmallMGC_Api_getConfigSA(self)
    def getConfigDigitmap(self): return _smallmgcapi.SmallMGC_Api_getConfigDigitmap(self)
    def getConfigGeneral(self): return _smallmgcapi.SmallMGC_Api_getConfigGeneral(self)
    def getConfigIp(self): return _smallmgcapi.SmallMGC_Api_getConfigIp(self)
    def startTest(self, *args): return _smallmgcapi.SmallMGC_Api_startTest(self, *args)
    def stopTest(self, *args): return _smallmgcapi.SmallMGC_Api_stopTest(self, *args)
    def getTestResult(self): return _smallmgcapi.SmallMGC_Api_getTestResult(self)
    def sendRawMessage(self, *args): return _smallmgcapi.SmallMGC_Api_sendRawMessage(self, *args)
    def getReceivedMessage(self, *args): return _smallmgcapi.SmallMGC_Api_getReceivedMessage(self, *args)
SmallMGC_Api_swigregister = _smallmgcapi.SmallMGC_Api_swigregister
SmallMGC_Api_swigregister(SmallMGC_Api)



